apiVersion: apps/v1
kind: Deployment
metadata:
    name: clouddevops
    namespace: default
    labels:
        app: clouddevops
spec:
    replicas: 3
    selector:
        matchLabels:
            app: clouddevops
    template:
        metadata:
            labels:
                app: clouddevops
        spec:
            containers:
                - name: clouddevops
                  image: erhansennx/cloud-dev-ops:latest
                  ports:
                      - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
    name: clouddevops
    namespace: default
spec:
    selector:
        app: clouddevops
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5000
    type: LoadBalancer
